### ISSUE TITLE
Add an event on closing 

### ISSUE THREAD

**Issue by salahturkmen** [Anuj2799/searchbar_animation#1]
Thank you for this wonderful package
Please can you add an event on closing

**Comment by anuj-patel-dev** [comment]
> Thank you for this wonderful package Please can you add an event on closing

Hello Salahturkmen,
Thank you for using my package. 
I will provide this in my next update.

**Comment by anuj-patel-dev** [comment]
> Thank you for this wonderful package Please can you add an event on closing

Hi @salahturkmen,
Are you talking about adding the event while searchbar is closing (i.e animation is still going backwards) or when searchbar is closed?

**Comment by salahturkmen** [comment]
> > Thank you for this wonderful package Please can you add an event on closing
> 
> Hi @salahturkmen,
> Are you talking about adding the event while searchbar is closing (that is animation is still is going backwards) or when searchbar is closed?

when searchbar is closed

**Comment by anuj-patel-dev** [comment]
Hi @salahturkmen,
I have added the feature you wanted, parameter names are "onExpansionComplete" and "onCollapseComplete".
I am closing this thread.
Thank you
