### ISSUE TITLE
from iconData to iconWidget

### ISSUE THREAD

**Issue by mrcnee93** [Anuj2799/searchbar_animation#4]
Hi, i'm using the searchbar as an action inside the AppBar, for UI consistency i set the button color, the searchborder color, the searchbox color ecc... to transparent.

now i have an icon similar to my other actions but i have no control on the icon style (the package accept icondata, not an icon widget).

can you please add the possibility to use an icon widget instead of simply passing icondata?

https://user-images.githubusercontent.com/63459992/194583156-b5dba769-9dc0-44c1-86f9-b59316c27a0c.mov

**Comment by anuj-patel-dev** [comment]
Hi @mrcnee93,
Thanks for using my package.
I'll definitely add icon widget for user to have an easy control over icons as well.
Thank you.

**Comment by anuj-patel-dev** [comment]
Hi @mrcnee93,
You can now have a full control over icons in the version 0.0.4.
Please have a look.
